---
# tasks file for apache
- name: "Instalacion de Apache"
  yum:
    name: httpd
    state: present

- name: "Arrancar el firewalld"
  service:
    name: firewalld
    state: started
    enabled: yes

- name: "Habilitar en el firewall el servicio httpd"
  firewalld:
    service: httpd
    permanent: yes
    state: enabled
    inmediate: yes

- name: "Creacion del archivo html"
  file:
    path: /var/www/html/index.html
    state: touch
    mode: "0765"
    owner: "root"

- name: "Contenido html"
  lineinfile:
    path: /var/www/html/index.html
    line: 'Bienvenido al servidor {{ ansible_fqdn }} el cual tiene la IP {{ ansible_default_ipv4.address }}'
  notify: reiniciar_apache